version: "3"

services:
  db:
    image: postgres
    container_name: IMPORT_DB
    restart: unless-stopped
    environment:
      - POSTGRES_DB=ImportDB
      - POSTGRES_USER=import_report
      - POSTGRES_PASSWORD=import_report
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5169:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: puma_import:latest
    restart: unless-stopped
    container_name: IMPORT_APP
    ports:
      - "8169:8169"
    volumes:
      - ./report_transport:/report_transport

    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8169"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ImportDB
      - DB_USER=import_report
      - DB_PASS=import_report
      - DB_PORT=5432
volumes:
  db_data:
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.75.0/24